{% set name = "codext" %}
{% set version = "1.8.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/codext-{{ version }}.tar.gz
  sha256: 968dbadd08eef092c8a987e6c37252fde1fca18cd52f78b7f01cee7900c63a94

build:
  noarch: python
  number: 0
  entry_points:
    - codext = codext:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - markdown2 >=2.4.0
    - python >=3.6
    - six

test:
  imports:
    - codext
    - codext.base
  commands:
    - pip check
    - codext --help
  requires:
    - pip

about:
  home: https://github.com/dhondta/python-codext
  summary: Native codecs extension
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
