{% set name = "codext" %}
{% set version = "1.15.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/codext-{{ version }}.tar.gz
  sha256: e5f251fc1ec6d24fd2208bca6854f994e06e8a73d57b8c70d19df0bcee4507d8

build:
  noarch: python
  number: 0
  entry_points:
    - codext = codext:main
    - unbase = codext.base.__init__:main
    - base1 = codext.base.baseN:main1
    - base2 = codext.base.baseN:main2
    - base3 = codext.base.baseN:main3
    - base4 = codext.base.baseN:main4
    - base8 = codext.base.baseN:main8
    - base10 = codext.base.baseN:main10
    - base16 = codext.base.baseN:main16
    - base26 = codext.base.baseN:main26
    - base32 = codext.base.baseN:main32
    - base32-hex = codext.base.baseN:main32hex
    - base32-geohash = codext.base.baseN:main32geo
    - base32-crockford = codext.base.baseN:main32crk
    - base32-z = codext.base.baseN:mainz32
    - base36 = codext.base.baseN:main36
    - base45 = codext.base.base45:main
    - base58-bitcoin = codext.base.baseN:main58bc
    - base58-ripple = codext.base.baseN:main58rp
    - base58-flickr = codext.base.baseN:main58fl
    - base62 = codext.base.baseN:main62
    - base63 = codext.base.baseN:main63
    - base64 = codext.base.baseN:main64
    - base64-url = codext.base.baseN:main64url
    - base67 = codext.base.baseN:main67
    - base85 = codext.base.base85:main85
    - base85-adobe = codext.base.base85:main85adobe
    - base85-xbtoa = codext.base.base85:main85xbtoa
    - base85-ipv6 = codext.base.base85:main85rfc1924
    - base85-xml = codext.base.base85:main85xml
    - base85-zeromq = codext.base.base85:main85zeromq
    - base91 = codext.base.base91:main91
    - base100 = codext.base.base100:main100
    - base122 = codext.base.base122:main122

  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
  run:
    - markdown2 >=2.4.0
    - python >={{ python_min }},<4.0

test:
  source_files:
    - tests
  imports:
    - codext
    - codext.base
    - codext.binary
    - codext.common
    - codext.compressions
    - codext.crypto
    - codext.hashing
    - codext.languages
    - codext.others
    - codext.stegano
  commands:
    - pip check
    - codext --help
    - unbase --help
    - base1 --help
    - base2 --help
    - base3 --help
    - base4 --help
    - base8 --help
    - base10 --help
    - base16 --help
    - base26 --help
    - base32 --help
    - base32-hex --help
    - base32-geohash --help
    - base32-crockford --help
    - base32-z --help
    - base36 --help
    - base45 --help
    - base58-bitcoin --help
    - base58-ripple --help
    - base58-flickr --help
    - base62 --help
    - base63 --help
    - base64 --help
    - base64-url --help
    - base67 --help
    - base85 --help
    - base85-adobe --help
    - base85-xbtoa --help
    - base85-ipv6 --help
    - base85-xml --help
    - base85-zeromq --help
    - base91 --help
    - base100 --help
    - base122 --help
    - pytest -vvv --capture=tee-sys -k "not hash_functions and not codec_base64 and not rank_input and not guess_decode" tests
  requires:
    - openssl
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/dhondta/python-codext
  doc_url: https://python-codext.readthedocs.io/en/latest/
  summary: Native codecs extension
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
